import tweet_data
from sys import exit
from config import create_api
from get_save_text import save_data

from tweepy import TweepError
from time import time, sleep, strftime, gmtime


'''
Tweets paintings and related metadata
'''

def get_latest_tweet_id(api):
    '''Gets tweet id, which is used to check whether a tweet was successful'''
    tweets = api.user_timeline(count=1)
    tweet_id = [tweet.id for tweet in tweets][0]
    return tweet_id

def send_tweet():
    '''
    Uses tweet data generated by the prepare_tweet_data() function to send a tweet
    '''
    # Retrieves data for the tweet
    image_name, image_path, status_text, tweeted_images_file_path = tweet_data.prepare_tweet_data()

    if image_path != '':
        # Creates API connection
        api = create_api()
        success = 0
        tweet_id_before = get_latest_tweet_id(api)

        tries = 2
        while tries > 0:
            # Makes two attempts to tweet the selected painting
            # If a tweet was made without error, uses the id of the latest tweet to check whether the attempt really was successful, 
            # updates the success variable, and returns the variable 
            # Or returns the initial value of the success variable at the end of the second unsuccessful attempt
            try:
                # Runs Tweepy command
                api.update_with_media(image_path, status=status_text)
                # Appends the name of the uploaded image to tweeted_images.txt
                save_data(tweeted_images_file_path, [image_name])
                tries = 0
            except (Exception, TweepError) as e:
                tries -= 1
                if e and tries == 1:
                    print(e)
                    print(
                        "  .. failed, sleeping for 5 seconds and then trying again")
                    sleep(5)

        tweet_id_after = get_latest_tweet_id(api)
        if tweet_id_after and tweet_id_before != tweet_id_after:
            print(f'Uploaded {image_name}...')
            success = 1
        return success

# Uses the send_tweet() function to upload five paintings 
attempts = 0
images_uploaded = 0
count_in_text = {1: "One image", 2: "Two images",
                 3: "Three images", 4: 'Four images', 5: 'Five images'}

while images_uploaded < 5:
    attempts += 1
    # Includes check to exit the while loop after 31 successful or unsuccessful attempts
    if attempts == 31:
        print(
            f'I have made {attempts} to retrieve and upload images. Exiting now.')
        exit(0)

    # Runs the command to send a tweet
    success = send_tweet()
    if success == 1:
        images_uploaded += 1
        if images_uploaded < 5:
            print(
                f'{count_in_text[images_uploaded]} uploaded until now...Will upload another in ...')

            # Uses a timer to maintain a gap of 1 hour between uploads
            for i in range(3600, -1, -1):
                start = time()
                print(f'\t{strftime("%H:%M:%S", gmtime(i))}', end='\r')
                sleep(1.0 - ((time() - start) % 1.0))
        else:
            print(
                f"I uploaded {count_in_text[images_uploaded].lower()} in this session. It was fun. I will be happy to work with you again.")

